sonar.projectKey=openaustralia_twfy
sonar.organization=openaustralia

sonar.sources=www,scripts,search
sonar.tests=tests
sonar.language=php
sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.php.tests.reportPath=coverage/junit.xml
sonar.php.codesniffer.reportPaths=coverage/phpcs.xml

sonar.exclusions=vendor/**,node_modules/**,**/test/**
sonar.test.exclusions=vendor/**,node_modules/**

sonar.cpd.php.minimumTokens=50
sonar.cpd.php.minimumLines=5
