#!/usr/bin/env bash
# Jobs that need running daily, that aren't with urgency dependent on new stuff
# from Hansard

source consts

# Update links info
# This loads the links with "mpinfoin.pl links" as well (so we're doing that twice)
../../openaustralia-parser/parse-member-links.rb

# Update MP info from Public Whip, FaxYourMP and other places
#cd ~/parlparse/members
#svn -q update
#cd ~/fawkes/scripts
./mpinfoin.pl

