#!/usr/bin/env bash
# Jobs that need running daily, that aren't with urgency dependent on new stuff
# from Hansard

source consts

# Update links info
# This loads the links with "mpinfoin.pl links" as well (so we're doing that twice)
../../openaustralia-parser/parse-member-links.rb

# Update MP info from Public Whip, FaxYourMP and other places
#cd ~/parlparse/members
#svn -q update
#cd ~/fawkes/scripts
# FIXME: Re-enable SSL verification by removing the setting of this environment variable
# This was disabled because we were getting "Can't connect to theyvoteforyou.org.au:443 (certificate verify failed)"
# on the server: https://github.com/openaustralia/openaustralia/issues/603#issuecomment-244642228
PERL_LWP_SSL_VERIFY_HOSTNAME=0 ./mpinfoin.pl
