#!/usr/bin/env bash

source consts

source ../../shlib/deployfns
read_conf "../conf/general"

BACKUP=$RAWDATA/backup

mkdir -p $BACKUP $BACKUP/firsts

# Keep much of last month, and first of month before then
# ... move first of month
touch $BACKUP/dummy-01.sql.bz2
mv $BACKUP/*-01.sql.bz2 $BACKUP/firsts
rm $BACKUP/firsts/dummy-01.sql.bz2
# ... delete all except 20
ls -1 twfy-all-including-sensitive-data-*.sql.bz2 | fgrep -v "`ls -1 twfy-all-including-sensitive-data-*.sql.bz2 | sort -n | tail -n 20`" | while read X
do
       #echo "Deleting old backup $X"
       rm $X
done

# Dumps database for backups (we do this last, so other servers can grab first
# of the month backup before it moves the next day)
mysqldump --skip-lock-tables -u $DB_USER --password=$DB_PASSWORD $DB_NAME | bzip2 -c > $BACKUP/openaustralia-all-including-sensitive-data-`date +%F`.sql.bz2


