#!/usr/bin/env bash
# morningupdate.  Called when new data is available from ukparse.

# Call with VERBOSE=true set in the environment for diagnostic messages:
# VERBOSE=true ./morningupdate

#set -x  # for debugging, prints each line before executing it

source consts
source ../../shlib/deployfns
read_conf "../conf/general"

[ -z "$VERBOSE" ] && VERBOSE=false

if $VERBOSE
then
	CRONQUIET_NODASH=""
else
	CRONQUIET_NODASH="cronquiet"
fi

# Make sure only one copy runs at once
if [ -z "$LOCKFILE" ]
then
    ./run-with-lockfile -n morningupdate-lockfile "$0"
    if [ $? = 100 ]
    then
            echo "Another copy of morningupdate or compactsearchdb is already running" 1>&2
    fi
    exit $?
fi

echo -n "Start time: "
date +"%Y-%m-%d %H:%M:%S %Z"

$VERBOSE && echo "Parsing from APH to XML and loading into the database"
../../openaustralia-parser/bin/run parse-speeches.rb previous-working-day


if [ -n "$XAPIANDB" ]; then
    # Update Xapan index
    $VERBOSE && echo "Xapian indexing"
    ../search/index.pl "$XAPIANDB" sincefile "$XAPIANDB/../searchdb-lastupdated" "$CRONQUIET_NODASH"
else
    echo "SKIPPED Xapian indexing: XAPIANDB is blank"
fi
# Create new RSS files.
if $VERBOSE
then
	echo "Running rssgenerate"
	./rssgenerate
else
 	at NOW >/dev/null 2>/dev/null <<EOF
./rssgenerate
EOF
fi

# Update the XML sitemaps to keep the search engines informed
../../openaustralia-parser/bin/run sitemap.rb

echo -n "Whole thing done time: "
date +"%Y-%m-%d %H:%M:%S"
